/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres';
import { relations } from '@payloadcms/db-postgres/drizzle';
import {
  boolean,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  serial,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
  type AnyPgColumn,
} from '@payloadcms/db-postgres/drizzle/pg-core';
export const enum_users_gender = pgEnum('enum_users_gender', ['male', 'female']);
export const enum_categories_type = pgEnum('enum_categories_type', ['product', 'post']);

export const media = pgTable(
  'media',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    alt: varchar('alt'),
    prefix: varchar('prefix').default('media'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
);

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const users = pgTable(
  'users',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    firstName: varchar('first_name').notNull(),
    middleName: varchar('middle_name'),
    lastName: varchar('last_name').notNull(),
    gender: enum_users_gender('gender').notNull().default('female'),
    paystackCustomerCode: varchar('paystack_customer_code'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    _verified: boolean('_verified'),
    _verificationToken: varchar('_verificationtoken'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index('users_first_name_idx').on(columns.firstName),
    index('users_middle_name_idx').on(columns.middleName),
    index('users_last_name_idx').on(columns.lastName),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
);

export const brands = pgTable(
  'brands',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    slugLock: boolean('slug_lock').notNull().default(true),
    srcImage: varchar('src_image'),
    image: uuid('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    srcUrl: varchar('src_url'),
    active: boolean('active').notNull().default(true),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('brands_title_idx').on(columns.title),
    index('brands_slug_idx').on(columns.slug),
    index('brands_image_idx').on(columns.image),
    index('brands_updated_at_idx').on(columns.updatedAt),
    index('brands_created_at_idx').on(columns.createdAt),
  ],
);

export const products = pgTable(
  'products',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    active: boolean('active').default(true),
    brand: uuid('brand_id')
      .notNull()
      .references(() => brands.id, {
        onDelete: 'set null',
      }),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    slugLock: boolean('slug_lock').notNull().default(true),
    origin: varchar('origin'),
    srcImage: varchar('src_image'),
    productInformation: varchar('product_information'),
    nutritionalInformation: varchar('nutritional_information'),
    srcUrl: varchar('src_url'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('products_brand_idx').on(columns.brand),
    index('products_slug_idx').on(columns.slug),
    index('products_updated_at_idx').on(columns.updatedAt),
    index('products_created_at_idx').on(columns.createdAt),
  ],
);

export const products_rels = pgTable(
  'products_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: uuid('media_id'),
    categoriesID: uuid('categories_id'),
  },
  (columns) => [
    index('products_rels_order_idx').on(columns.order),
    index('products_rels_parent_idx').on(columns.parent),
    index('products_rels_path_idx').on(columns.path),
    index('products_rels_media_id_idx').on(columns.mediaID),
    index('products_rels_categories_id_idx').on(columns.categoriesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'products_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'products_rels_categories_fk',
    }).onDelete('cascade'),
  ],
);

export const product_lines = pgTable(
  'product_lines',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    slug: varchar('slug').notNull(),
    slugLock: boolean('slug_lock').notNull().default(true),
    sku: varchar('sku').notNull(),
    active: boolean('active').notNull().default(true),
    title: varchar('title').notNull(),
    size: varchar('size'),
    flavorColor: varchar('flavor_color'),
    variant: varchar('variant'),
    product: uuid('product_id')
      .notNull()
      .references(() => products.id, {
        onDelete: 'set null',
      }),
    category: varchar('category'),
    srcPrice: numeric('src_price', { mode: 'number' }),
    srcDiscountedPrice: numeric('src_discounted_price', { mode: 'number' }),
    retailPrice: numeric('retail_price', { mode: 'number' }),
    wholesalePrice: numeric('wholesale_price', { mode: 'number' }),
    stock: numeric('stock', { mode: 'number' }).notNull().default(0),
    srcStock: numeric('src_stock', { mode: 'number' }),
    onPallet: numeric('on_pallet', { mode: 'number' }),
    inCase: numeric('in_case', { mode: 'number' }),
    expiryDate: timestamp('expiry_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    weight: numeric('weight', { mode: 'number' }),
    servingSizePerContainer: numeric('serving_size_per_container', { mode: 'number' }),
    servingSize: numeric('serving_size', { mode: 'number' }),
    srcProductCode: varchar('src_product_code'),
    barcode: varchar('barcode'),
    exportCommodityCode: varchar('export_commodity_code'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('product_lines_slug_idx').on(columns.slug),
    uniqueIndex('product_lines_sku_idx').on(columns.sku),
    index('product_lines_title_idx').on(columns.title),
    index('product_lines_product_idx').on(columns.product),
    index('product_lines_barcode_idx').on(columns.barcode),
    index('product_lines_updated_at_idx').on(columns.updatedAt),
    index('product_lines_created_at_idx').on(columns.createdAt),
  ],
);

export const product_lines_rels = pgTable(
  'product_lines_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: uuid('media_id'),
  },
  (columns) => [
    index('product_lines_rels_order_idx').on(columns.order),
    index('product_lines_rels_parent_idx').on(columns.parent),
    index('product_lines_rels_path_idx').on(columns.path),
    index('product_lines_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [product_lines.id],
      name: 'product_lines_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'product_lines_rels_media_fk',
    }).onDelete('cascade'),
  ],
);

export const categories_type = pgTable(
  'categories_type',
  {
    order: integer('order').notNull(),
    parent: uuid('parent_id').notNull(),
    value: enum_categories_type('value'),
    id: uuid('id').defaultRandom().primaryKey(),
  },
  (columns) => [
    index('categories_type_order_idx').on(columns.order),
    index('categories_type_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [categories.id],
      name: 'categories_type_parent_fk',
    }).onDelete('cascade'),
  ],
);

export const categories_breadcrumbs = pgTable(
  'categories_breadcrumbs',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    doc: uuid('doc_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    url: varchar('url'),
    label: varchar('label'),
  },
  (columns) => [
    index('categories_breadcrumbs_order_idx').on(columns._order),
    index('categories_breadcrumbs_parent_id_idx').on(columns._parentID),
    index('categories_breadcrumbs_doc_idx').on(columns.doc),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [categories.id],
      name: 'categories_breadcrumbs_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const categories = pgTable(
  'categories',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    slug: varchar('slug').notNull(),
    slugLock: boolean('slug_lock').notNull().default(true),
    title: varchar('title').notNull(),
    description: varchar('description'),
    srcUrl: varchar('src_url'),
    active: boolean('active').default(true),
    parent: uuid('parent_id').references((): AnyPgColumn => categories.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('categories_slug_idx').on(columns.slug),
    index('categories_parent_idx').on(columns.parent),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
);

export const carts_items = pgTable(
  'carts_items',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    productLines: uuid('product_lines_id')
      .notNull()
      .references(() => product_lines.id, {
        onDelete: 'set null',
      }),
    quantity: numeric('quantity', { mode: 'number' }).notNull(),
  },
  (columns) => [
    index('carts_items_order_idx').on(columns._order),
    index('carts_items_parent_id_idx').on(columns._parentID),
    index('carts_items_product_lines_idx').on(columns.productLines),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [carts.id],
      name: 'carts_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const carts = pgTable(
  'carts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    user: uuid('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    sessionId: varchar('session_id'),
    total: numeric('total', { mode: 'number' }).notNull().default(0),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('carts_user_idx').on(columns.user),
    index('carts_updated_at_idx').on(columns.updatedAt),
    index('carts_created_at_idx').on(columns.createdAt),
  ],
);

export const stock_alerts = pgTable(
  'stock_alerts',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    user: uuid('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    productLine: uuid('product_line_id')
      .notNull()
      .references(() => product_lines.id, {
        onDelete: 'set null',
      }),
    notificationCount: numeric('notification_count', { mode: 'number' }).default(0),
    lastNotifiedAt: timestamp('last_notified_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('stock_alerts_user_idx').on(columns.user),
    index('stock_alerts_product_line_idx').on(columns.productLine),
    index('stock_alerts_updated_at_idx').on(columns.updatedAt),
    index('stock_alerts_created_at_idx').on(columns.createdAt),
  ],
);

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: uuid('media_id'),
    usersID: uuid('users_id'),
    brandsID: uuid('brands_id'),
    productsID: uuid('products_id'),
    'product-linesID': uuid('product_lines_id'),
    categoriesID: uuid('categories_id'),
    cartsID: uuid('carts_id'),
    'stock-alertsID': uuid('stock_alerts_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_brands_id_idx').on(columns.brandsID),
    index('payload_locked_documents_rels_products_id_idx').on(columns.productsID),
    index('payload_locked_documents_rels_product_lines_id_idx').on(
      columns['product-linesID'],
    ),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_carts_id_idx').on(columns.cartsID),
    index('payload_locked_documents_rels_stock_alerts_id_idx').on(
      columns['stock-alertsID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['brandsID']],
      foreignColumns: [brands.id],
      name: 'payload_locked_documents_rels_brands_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['product-linesID']],
      foreignColumns: [product_lines.id],
      name: 'payload_locked_documents_rels_product_lines_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cartsID']],
      foreignColumns: [carts.id],
      name: 'payload_locked_documents_rels_carts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['stock-alertsID']],
      foreignColumns: [stock_alerts.id],
      name: 'payload_locked_documents_rels_stock_alerts_fk',
    }).onDelete('cascade'),
  ],
);

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: uuid('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
);

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
);

export const nav_items = pgTable(
  'nav_items',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    url: varchar('url').notNull(),
  },
  (columns) => [
    index('nav_items_order_idx').on(columns._order),
    index('nav_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [nav.id],
      name: 'nav_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
);

export const nav = pgTable('nav', {
  id: uuid('id').defaultRandom().primaryKey(),
  updatedAt: timestamp('updated_at', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp('created_at', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_media = relations(media, () => ({}));
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}));
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}));
export const relations_brands = relations(brands, ({ one }) => ({
  image: one(media, {
    fields: [brands.image],
    references: [media.id],
    relationName: 'image',
  }),
}));
export const relations_products_rels = relations(products_rels, ({ one }) => ({
  parent: one(products, {
    fields: [products_rels.parent],
    references: [products.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [products_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
  categoriesID: one(categories, {
    fields: [products_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
}));
export const relations_products = relations(products, ({ one, many }) => ({
  brand: one(brands, {
    fields: [products.brand],
    references: [brands.id],
    relationName: 'brand',
  }),
  _rels: many(products_rels, {
    relationName: '_rels',
  }),
}));
export const relations_product_lines_rels = relations(product_lines_rels, ({ one }) => ({
  parent: one(product_lines, {
    fields: [product_lines_rels.parent],
    references: [product_lines.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [product_lines_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}));
export const relations_product_lines = relations(product_lines, ({ one, many }) => ({
  product: one(products, {
    fields: [product_lines.product],
    references: [products.id],
    relationName: 'product',
  }),
  _rels: many(product_lines_rels, {
    relationName: '_rels',
  }),
}));
export const relations_categories_type = relations(categories_type, ({ one }) => ({
  parent: one(categories, {
    fields: [categories_type.parent],
    references: [categories.id],
    relationName: 'type',
  }),
}));
export const relations_categories_breadcrumbs = relations(
  categories_breadcrumbs,
  ({ one }) => ({
    _parentID: one(categories, {
      fields: [categories_breadcrumbs._parentID],
      references: [categories.id],
      relationName: 'breadcrumbs',
    }),
    doc: one(categories, {
      fields: [categories_breadcrumbs.doc],
      references: [categories.id],
      relationName: 'doc',
    }),
  }),
);
export const relations_categories = relations(categories, ({ one, many }) => ({
  type: many(categories_type, {
    relationName: 'type',
  }),
  breadcrumbs: many(categories_breadcrumbs, {
    relationName: 'breadcrumbs',
  }),
  parent: one(categories, {
    fields: [categories.parent],
    references: [categories.id],
    relationName: 'parent',
  }),
}));
export const relations_carts_items = relations(carts_items, ({ one }) => ({
  _parentID: one(carts, {
    fields: [carts_items._parentID],
    references: [carts.id],
    relationName: 'items',
  }),
  productLines: one(product_lines, {
    fields: [carts_items.productLines],
    references: [product_lines.id],
    relationName: 'productLines',
  }),
}));
export const relations_carts = relations(carts, ({ one, many }) => ({
  user: one(users, {
    fields: [carts.user],
    references: [users.id],
    relationName: 'user',
  }),
  items: many(carts_items, {
    relationName: 'items',
  }),
}));
export const relations_stock_alerts = relations(stock_alerts, ({ one }) => ({
  user: one(users, {
    fields: [stock_alerts.user],
    references: [users.id],
    relationName: 'user',
  }),
  productLine: one(product_lines, {
    fields: [stock_alerts.productLine],
    references: [product_lines.id],
    relationName: 'productLine',
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    brandsID: one(brands, {
      fields: [payload_locked_documents_rels.brandsID],
      references: [brands.id],
      relationName: 'brands',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
    'product-linesID': one(product_lines, {
      fields: [payload_locked_documents_rels['product-linesID']],
      references: [product_lines.id],
      relationName: 'product-lines',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    cartsID: one(carts, {
      fields: [payload_locked_documents_rels.cartsID],
      references: [carts.id],
      relationName: 'carts',
    }),
    'stock-alertsID': one(stock_alerts, {
      fields: [payload_locked_documents_rels['stock-alertsID']],
      references: [stock_alerts.id],
      relationName: 'stock-alerts',
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: '_rels',
    }),
  }),
);
export const relations_payload_migrations = relations(payload_migrations, () => ({}));
export const relations_nav_items = relations(nav_items, ({ one }) => ({
  _parentID: one(nav, {
    fields: [nav_items._parentID],
    references: [nav.id],
    relationName: 'items',
  }),
}));
export const relations_nav = relations(nav, ({ many }) => ({
  items: many(nav_items, {
    relationName: 'items',
  }),
}));

type DatabaseSchema = {
  enum_users_gender: typeof enum_users_gender;
  enum_categories_type: typeof enum_categories_type;
  media: typeof media;
  users_sessions: typeof users_sessions;
  users: typeof users;
  brands: typeof brands;
  products: typeof products;
  products_rels: typeof products_rels;
  product_lines: typeof product_lines;
  product_lines_rels: typeof product_lines_rels;
  categories_type: typeof categories_type;
  categories_breadcrumbs: typeof categories_breadcrumbs;
  categories: typeof categories;
  carts_items: typeof carts_items;
  carts: typeof carts;
  stock_alerts: typeof stock_alerts;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  nav_items: typeof nav_items;
  nav: typeof nav;
  relations_media: typeof relations_media;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_brands: typeof relations_brands;
  relations_products_rels: typeof relations_products_rels;
  relations_products: typeof relations_products;
  relations_product_lines_rels: typeof relations_product_lines_rels;
  relations_product_lines: typeof relations_product_lines;
  relations_categories_type: typeof relations_categories_type;
  relations_categories_breadcrumbs: typeof relations_categories_breadcrumbs;
  relations_categories: typeof relations_categories;
  relations_carts_items: typeof relations_carts_items;
  relations_carts: typeof relations_carts;
  relations_stock_alerts: typeof relations_stock_alerts;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_nav_items: typeof relations_nav_items;
  relations_nav: typeof relations_nav;
};

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
